- hosts: test-1
  user: vijay
  become: yes
  connection: ssh
#  gather_facts: no
#  vars:
#   playbook_version: 0.1b
#  vars_files:
#   - conf/copyright.yml
#   - conf/webdefaults.yml
#  vars_prompt:
#  #   - name: web_domain
#  #     prompt: Web Domain
  vars:
    packages:
    - tree
    - java-1.8.0-openjdk-devel
  tasks:
  - name: Install packages
    yum: pkg={{ packages }} state=installed update_cache=true
#    with_items:
#    - tree
#    - java-1.8.0-openjdk-devel
  roles:
#  - apache-httpd
  - { role: apache-httpd, when: "ansible_os_family == 'RedHat'"}
  - { role: debian_webserver, when: "ansible_os_family == 'Debian'"}
